### ISSUE TITLE
Cannot find Chrome binary

### ISSUE THREAD

**Issue by marcinbauer-ohf** [pacjo/UTnotifier#3]
Recently I've been having problems running the script. It was running for a few months, but now it crashes.
I think I just updated my Chrome browser, other than that nothing has changed.
I tried to upgrade all of my brew packages, python, selenium, and web driver, but still I get this error.

`Traceback (most recent call last):
  File "/Users/marcinbauer/Downloads/UTnotifier-main/UTnotifier.py", line 141, in <module>
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
    super().__init__(
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
    super().__init__(
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
0   chromedriver                        0x0000000102f4e924 chromedriver + 4303140
1   chromedriver                        0x0000000102f47050 chromedriver + 4272208
2   chromedriver                        0x0000000102b7b328 chromedriver + 291624
3   chromedriver                        0x0000000102ba3a7c chromedriver + 457340
4   chromedriver                        0x0000000102ba2ffc chromedriver + 454652
5   chromedriver                        0x0000000102be2040 chromedriver + 712768
6   chromedriver                        0x0000000102be180c chromedriver + 710668
7   chromedriver                        0x0000000102bac8d4 chromedriver + 493780
8   chromedriver                        0x0000000102bad71c chromedriver + 497436
9   chromedriver                        0x0000000102f0f7dc chromedriver + 4044764
10  chromedriver                        0x0000000102f13d20 chromedriver + 4062496
11  chromedriver                        0x0000000102f19f40 chromedriver + 4087616
12  chromedriver                        0x0000000102f14824 chromedriver + 4065316
13  chromedriver                        0x0000000102eecd1c chromedriver + 3902748
14  chromedriver                        0x0000000102f30414 chromedriver + 4178964
15  chromedriver                        0x0000000102f3056c chromedriver + 4179308
16  chromedriver                        0x0000000102f40830 chromedriver + 4245552
17  libsystem_pthread.dylib             0x000000019a0c3fa8 _pthread_start + 148
18  libsystem_pthread.dylib             0x000000019a0beda0 thread_start + 8
`

**Comment by pacjo** [comment]
I will try to take a look, but I hate working on this project. The code is a mess and I already tried refactoring it twice without any good results. It's been long since I last used User testing and I'm not sure code still works overall (not just webdriver initialization you have issues with).

**Comment by pacjo** [comment]
Sorry, closed by mistake. I will take a look.

**Comment by marcinbauer-ohf** [comment]
I think this was something wrong on googles webdriver side? Because I didn't do anything and it started to work again. Thanks for checking!

**Comment by pacjo** [comment]
Yea, I like issues that solve themselves. Closing.
